config/routes.rb
require 'sidekiq/web'

Catarse::Application.routes.draw do
  def ssl_options
    if Rails.env.production? && CatarseSettings.get_without_cache(:secure_host)
      {protocol: 'https', host: CatarseSettings.get_without_cache(:secure_host)}
    else
      {}
    end
  end

  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords },
      defaults: ssl_options
    }
  )


  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}.merge(ssl_options)
  end


  get '/thank_you' => "static#thank_you"
  get '/termos-de-uso' => "static#termos_de_uso"
  get '/como-funciona' => "static#como_funciona"
  get '/quem-somos' => "static#quem_somos"

  check_user_admin = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin }

  filter :locale, exclude: /\/auth\//

  # Mountable engines
  constraints check_user_admin do
    mount Sidekiq::Web => '/sidekiq'
  end

  #mount CatarsePaypalExpress::Engine => "/", as: :catarse_paypal_express
  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarseCredits::Engine => "/", as: :catarse_credits
  #  mount CatarseWepay::Engine => "/", as: :catarse_wepay

  get '/post_preview' => 'post_preview#show', as: :post_preview
  resources :projects, only: [:index, :create, :update, :new, :show] do
    resources :posts, controller: 'projects/posts', only: [ :index, :create, :destroy ]
    resources :rewards, only: [ :index, :create, :update, :destroy, :new, :edit ] do
      member do
        post 'sort'
      end
    end
    resources :contributions, {controller: 'projects/contributions'}.merge(ssl_options) do
      member do
        put 'credits_checkout'
      end
    end
    collection do
      get 'video'
    end
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      get :metrics, to: 'projects/metrics#index'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
    end
  end
  resources :users do
    resources :projects, controller: 'users/projects', only: [ :index ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :reactivate
    end
    resources :contributions, controller: 'users/contributions', only: [:index] do
      member do
        get :request_refund
      end
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password', ssl_options
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  

  # Channels
  constraints SubdomainConstraint do
    namespace :channels, path: '' do

      namespace :admin do
        namespace :reports do
          resources :subscriber_reports, only: [ :index ]
        end
        resources :posts
        resources :partners
        resources :followers, only: [ :index ]
      end

      resources :posts
      get '/', to: 'profiles#show', as: :profile
      get '/how-it-works', to: 'profiles#how_it_works', as: :about
      resource :profile
      # NOTE We use index instead of create to subscribe comming back from auth via GET
      resource :channels_subscriber, only: [:show, :destroy], as: :subscriber
    end
  end

  # Root path should be after channel constraints
   
   #root to: 'projects#index'
   root to: 'high_voltage/pages#show', id: 'maintenance'

  get "/explore" => "explore#index", as: :explore

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :statistics, only: [ :index ]
    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        put 'confirm'
        put 'pendent'
        put 'change_reward'
        put 'refund'
        put 'hide'
        put 'cancel'
        put 'push_to_trash'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/shared/catarse_auto_html.rb
module Shared::CatarseAutoHtml
  extend ActiveSupport::Concern

  included do
    AutoHtml.add_filter(:email_image).with(width: 200) do |text, options|
      text.gsub(/http(s)?:\/\/.+\.(jpg|jpeg|bmp|gif|png)(\?\S+)?/i) do |match|
        width = options[:width]
        %|<img src="#{match}" alt="" style="max-width:#{width}px" />|
      end
    end

    def self.catarse_auto_html_for options={}
      self.auto_html_for options[:field] do
        html_escape map: {
          '&' => '&amp;',
          '>' => '&gt;',
          '<' => '&lt;',
          '"' => '"'
        }
        image
        youtube width: options[:video_width], height: options[:video_height], wmode: "opaque"
        vimeo width: options[:video_width], height: options[:video_height]
        redcloth target: :_blank
        link target: :_blank
      end
    end

    def catarse_email_auto_html_for field_data, options= {}
      self.auto_html field_data do
        html_escape map: {
          '&' => '&amp;',
          '>' => '&gt;',
          '<' => '&lt;',
          '"' => '"'
        }
        email_image width: options[:image_width]
        redcloth target: :_blank
        link target: :_blank
      end
    end
  end
end

app/models/concerns/shared/chart_handler.rb
module Shared::ChartHandler
  extend ActiveSupport::Concern

  included do
    def self.chart
      series = [
        {name: I18n.t('admin.statistics.charts.current_period'), data: {}},
        {name: I18n.t('admin.statistics.charts.last_year'), data: {}}
      ]
      self.all.each do |data|
        series[0][:data][data.label] = data.current_year
        series[1][:data][data.label] = data.last_year
      end
      series
    end

  end
end

app/models/concerns/shared/queued.rb
module Shared::Queued
  extend ActiveSupport::Concern

  included do

    def remove_scheduled_job(worker_class_name, first_arg_c = self.id)
      on_scheduled_jobs(worker_class_name, first_arg_c) do |job|
        job.delete
      end
    end

    private

    def on_scheduled_jobs(class_name, first_arg_c)
      scheduled_queue.each do |job|
        yield job if job_match?(job, class_name, first_arg_c)
      end
    end

    def job_match?(job, class_name, first_arg_c)
      job['class'] == class_name && job['args'][0] == first_arg_c
    end

    def scheduled_queue
      Sidekiq::ScheduledSet.new
    end

  end
end

app/models/concerns/shared/state_machine_helpers.rb
require 'state_machine'
module Shared
  module StateMachineHelpers
    extend ActiveSupport::Concern

    included do
      def self.state_names
        self.state_machine.states.map do |state|
          state.name if state.name != :deleted
        end.compact!
      end
    end
  end
end

app/models/concerns/shared/video_handler.rb
module Shared::VideoHandler
  extend ActiveSupport::Concern

  included do
    validates_format_of :video_url, with: /(https?\:\/\/|)(youtu(\.be|be\.com)|vimeo).*+/, message: I18n.t('project.video_regex_validation'), allow_blank: true

    def video
      @video ||= VideoInfo.get(self.video_url) if self.video_url.present?
    end

    def video_valid?
      self.video_url.present? && self.video
    end

    def display_video_embed_url
      if self.video_embed_url
        "#{self.video_embed_url}?title=0&byline=0&portrait=0&autoplay=0"
      end
    end

    def update_video_embed_url
      self.video_embed_url = self.video.embed_url if self.video_valid?
      self.save
    end
  end

end

app/views/custom/catarse_bootstrap/shared/_feedback.html.slim
.feedback-box.feedback-box-closed
  p#title.body-big.title
    = t('.texts.title')
  p#description.body-small
    = t('.texts.content').html_safe

  .w-form
    = form_tag(feedbacks_path(format: :json), method: :post, remote: true) do
      = email_field_tag("feedback[email]", content = (current_user.try(:email)), options = { class: 'w-input text-field', placeholder: t('.placeholders.email')})
      = text_area_tag("feedback[message]", content = nil, options = {class: 'w-input text-field text-field-feedback', placeholder: t('.placeholders.text')})

      = submit_tag(value = t('.inputs.submit'), options = {class: 'w-button button bt-medium bt-dark'})

  / Conteúdo que deve entrar quando o form for enviado, tudo acima deve esconder
  p#thanks-title.display-medium = t('.texts.response.title').html_safe
  p#thanks-description.body-medium = t('.texts.response.content')

  = link_to "#", class: "close-button" do
    = image_tag 'catarse_bootstrap/icons/icon-close.png'

= link_to "#", class: "icon-feedback-box" do
  = image_tag 'catarse_bootstrap/icons/feedback-box-icon.png'

app/views/custom/catarse_bootstrap/shared/_footer.html.slim
footer
  .row
    .large-3.columns
      h3.footer-title= t('footer.titles.contact')
      ul.footer-list
        li= link_to t('footer.links.twitter'), "#{CatarseSettings[:twitter_url]}", target: '_blank'
        li= link_to t('footer.links.facebook'), "#{CatarseSettings[:facebook_url]}", target: '_blank'
        li= link_to t('footer.links.instagram'), "#{CatarseSettings[:instagram_url]}", target: '_blank'
        li= link_to t('footer.links.github'), "#{CatarseSettings[:github_url]}", target: '_blank'
        li= link_to t('footer.links.blog'), "#{CatarseSettings[:blog_url]}", target: '_blank'
        li.zendesk_widget= link_to t('footer.links.contact'), "#{CatarseSettings[:zendesk_url]}/account/dropboxes/#{CatarseSettings[:zendesk_dropbox_id]}"
    .large-3.columns
      h3.footer-title= t('footer.titles.about')
      ul.footer-list
        li= link_to t('footer.links.faq'), "#{CatarseSettings[:faq_url]}", target: '_blank'
        li= link_to t('footer.links.feedback'), "#{CatarseSettings[:feedback_url]}", target: '_blank'
        li= link_to t('footer.links.terms'), terms_of_use_path, target: '_blank'
        li= link_to t('footer.links.privacy'), privacy_policy_path, target: '_blank'
    .large-3.columns
      h3.footer-title= t('footer.titles.sitemap')
      ul.footer-list
        li= link_to t('footer.links.submit'), start_path
        li= link_to t('footer.links.discover'), explore_path
        - if current_user
          li= link_to t('footer.links.near'), explore_path(anchor: "near_of/#{current_user.address_state}")
        li= link_to t('footer.links.recommended'), explore_path(anchor: "recommended")
        li= link_to t('footer.links.expiring'), explore_path(anchor: "expiring")
        li= link_to t('footer.links.recents'), explore_path(anchor: "recent")
    .large-3.columns
      h3.footer-title= t('footer.titles.newsletter')
      .newsletter-footer
        = render 'layouts/newsletter'
      h3.footer-title= t('footer.titles.social')
      .twitter-box
        = link_to "Follow @#{CatarseSettings[:twitter_username]}", "http://twitter.com/#{CatarseSettings[:twitter_username]}", :class => 'twitter-follow-button', :"data-button"=>"blue", :"data-text-color" => "#ffffff", :"data-link-color"=>"#fffffff", :"data-width" => "224px"
      .facebook-box
        = render_facebook_like href: "", colorscheme: "dark", width: "171"
  .row
    hr/
  .row
    p.copyleft= "#{t('footer.texts.copyleft')} Catarse, #{DateTime.now.year} | Open source #{link_to 'Catarse @ Github', "#{CatarseSettings[:github_url]}", :class => 'github', target: '_blank'}".html_safe
footer.w-hidden-small.w-hidden-tiny.footer-simple
  .w-container
    .footer-signature-text.caption #{CatarseSettings[:comapny_name]} #{Time.now.strftime("%Y")}
    ul.w-list-unstyled.footer-simple-links.caption
      li.footer-simple-links-list = link_to t('footer.links.blog'), CatarseSettings[:blog_url], class: "link-footer"
      li.footer-simple-links-list = link_to t('footer.links.discover'), explore_path, class: "link-footer"
      li.footer-simple-links-list = link_to t('footer.links.start'), start_path, class: "link-footer"
      li.footer-simple-links-list = link_to t('footer.links.faq'), CatarseSettings[:faq_url], class: "link-footer"
      li.footer-simple-links-list = link_to t('footer.links.feedback'), CatarseSettings[:feedback_url], class: "link-footer"
      li.footer-simple-links-list = link_to t('footer.links.terms'), terms_of_use_path, class: "link-footer"
      li.footer-simple-links-list = link_to t('footer.links.privacy'), privacy_policy_path, class: "link-footer"

app/views/custom/catarse_bootstrap/shared/_footer_big.html.slim
#footer
  .container
    .row
      .col-md-3
        a href="#" 
          img alt="" src="/assets_xodo/img/footer-logo.png" style=("margin-bottom: 20px;") /
      .col-md-3
        h3 Saiba Mais:
        ul.list-unstyled
          li
            a href="#"  Sobre Nós
          li
            a href="#"  Xodó na Mídia
          li
            a href="#"  Termos de Uso
          li
            a href="#"  Fale Conosco
      .col-md-3
        h3 navegue:
        ul.list-unstyled
          li
            a href="#"  Como Funciona
          li
            a href="#"  Envie seu Projeto
          li
            a href="#"  Explore Projetos
          li
            a href="#"  Quem Xodozou
      .col-md-3
        h3
          | siga nossas
          br redes sociais::
        ul.list-unstyled
          li
            a href="#" 
              img src="/assets_xodo/img/nav-face.png"  Facebook
          li
            a href="#" 
              img src="/assets_xodo/img/nav-twitter.png"  Twitter
          li
            a href="#" 
              img src="/assets_xodo/img/nav-instagram.png"  Instagram
    .row
      .footer-copyright Copyright© 2014 Xodó - Todos os direitos reservados

app/views/custom/catarse_bootstrap/shared/_footer_bootstrap_v1.html.slim
footer
  .row
    .large-3.columns
      h3.footer-title= t('footer.titles.contact')
      ul.footer-list
        li= link_to t('footer.links.twitter'), "#{CatarseSettings[:twitter_url]}", target: '_blank'
        li= link_to t('footer.links.facebook'), "#{CatarseSettings[:facebook_url]}", target: '_blank'
        li= link_to t('footer.links.instagram'), "#{CatarseSettings[:instagram_url]}", target: '_blank'
        li= link_to t('footer.links.github'), "#{CatarseSettings[:github_url]}", target: '_blank'
        li= link_to t('footer.links.blog'), "#{CatarseSettings[:blog_url]}", target: '_blank'
        li.zendesk_widget= link_to t('footer.links.contact'), "#{CatarseSettings[:zendesk_url]}/account/dropboxes/#{CatarseSettings[:zendesk_dropbox_id]}"
    .large-3.columns
      h3.footer-title= t('footer.titles.about')
      ul.footer-list
        li= link_to t('footer.links.faq'), "#{CatarseSettings[:faq_url]}", target: '_blank'
        li= link_to t('footer.links.feedback'), "#{CatarseSettings[:feedback_url]}", target: '_blank'
        li= link_to t('footer.links.terms'), terms_of_use_path, target: '_blank'
        li= link_to t('footer.links.privacy'), privacy_policy_path, target: '_blank'
    .large-3.columns
      h3.footer-title= t('footer.titles.sitemap')
      ul.footer-list
        li= link_to t('footer.links.submit'), page_path(:how_it_works)
        li= link_to t('footer.links.discover'), explore_path
        - if current_user
          li= link_to t('footer.links.near'), explore_path(anchor: "near_of/#{current_user.address_state}")
        li= link_to t('footer.links.recommended'), explore_path(anchor: "recommended")
        li= link_to t('footer.links.expiring'), explore_path(anchor: "expiring")
        li= link_to t('footer.links.recents'), explore_path(anchor: "recent")
    .large-3.columns
      h3.footer-title= t('footer.titles.newsletter')
      .newsletter-footer
        = render 'layouts/newsletter'
      h3.footer-title= t('footer.titles.social')
      .twitter-box
        = link_to "Follow @#{CatarseSettings[:twitter_username]}", "http://twitter.com/#{CatarseSettings[:twitter_username]}", :class => 'twitter-follow-button', :"data-button"=>"blue", :"data-text-color" => "#ffffff", :"data-link-color"=>"#fffffff", :"data-width" => "224px"
      .facebook-box
        = render_facebook_like href: "", colorscheme: "dark", width: "171"
  .row
    hr/
  .row
    p.copyleft= "#{t('footer.texts.copyleft')} Catarse, #{DateTime.now.year} | Open source #{link_to 'Catarse @ Github', "#{CatarseSettings[:github_url]}", :class => 'github', target: '_blank'}".html_safe

app/views/custom/catarse_bootstrap/shared/_footer_channel.html.slim
.channel_footer
  .row
    .large-12.columns
      nav
        ul.nav-horizontal
          li.nav-item.separator
            = link_to t('.terms'), channel.terms_url, title: t('.terms'), class: 'standard-link', target: '_blank'
          li.nav-item.separator
            = link_to t('.privacy_policy'), privacy_policy_path, title: t('.privacy_policy'), class: 'standard-link', target: '_blank'
          li.nav-item.separator
            = link_to t('.how_works', name: channel.name), channels_about_path, title: t('.how_it_works', name: channel.name), class: 'standard-link'
          li.nav-item.separator
            = mail_to channel.email, t('.contact'), title: t('.contact'), class: 'standard-link', target: '_blank'
          li.nav-item
            = link_to t('.what_is_channel'), CatarseSettings[:about_channel_url], title: t('.how_channels_work'), class: 'standard-link', target: '_blank'

app/views/custom/catarse_bootstrap/shared/_header.html.slim
header.main-header
  .w-row
    .w-col.w-col-6.w-clearfix
      = link_to root_path do
        = link_to (image_tag "/assets_xodo/img/logo.png"), root_url(host: CatarseSettings[:base_domain] || request.domain), class: 'header-logo', :title => CatarseSettings[:company_name]
    .w-col.w-col-6

app/views/custom/catarse_bootstrap/shared/_header_big.html.slim
.main-header
  .w-row
    .w-col.w-col-2.w-col-small-4.w-col-tiny-4
      = link_to (image_tag "catarse_bootstrap/catarse-logo.png"), root_url(host: CatarseSettings[:base_domain] || request.domain), class: 'header-logo', :title => CatarseSettings[:company_name]
    .header-nav.w-col.w-col-10.w-col-small-8.w-col-tiny-8
      = link_to t('layouts.header.discover'), explore_path, class: 'header-link left-side no-mobile'

      = link_to t('layouts.header.submit'), start_path, class: 'header-link left-side no-mobile'

      .user-profile
        - if current_user
          = link_to '#', class: 'user-options' do
            = image_tag(current_user.display_image, :size => "40x40", class: 'user-avatar')
          ul.user-nav
            li= link_to t('layouts.header.profile'), current_user
            li= link_to t('layouts.user.my_contributions'), user_path(current_user, anchor: 'contributions')
            - if current_user.project_owner?
              li= link_to t('.projects'), user_path(current_user, anchor: 'projects')
            li
              = link_to t('layouts.user.my_credits'), user_path(current_user, anchor: 'credits')
              .small
                | (#{current_user.display_credits})
            li
              = link_to t('layouts.user.refund_link'), user_path(current_user, anchor: 'credits')
            - if current_user.admin? || current_user.channel
              li.divider
              - for menu, path in controller.menu do
                li= link_to menu, path
            li.divider= link_to t('layouts.user.logout'), destroy_user_session_path, method: :delete
        - else
            = link_to t('layouts.header.signin'), new_user_session_url, class: 'header-link right-side no-mobile'

            = link_to t('layouts.header.signup'), new_user_registration_url, class: 'header-link right-side no-mobile'

      = link_to t('layouts.header.help'), CatarseSettings[:support_forum], target: :_blank, class: 'header-link right-side no-mobile',  id: 'guidelines_header_modal' if CatarseSettings[:support_forum].present?

      .w-form.form-search.no-mobile
        = form_tag explore_path, :method => 'GET', :class=>'discover-form' do
          = text_field_tag :pg_search, nil, autocomplete: "off", value: params[:pg_search], class: "form-search-input", placeholder: t('layouts.header.search')
          = submit_tag class: "form-search-image"


      = link_to 'Menu', '#', class: 'mobile-menu-link'

ul.mobile-menu
  li
    = link_to t('layouts.header.signup'), new_user_registration_url, class: 'header-link right-side'

  li
    = link_to t('layouts.header.signin'), new_user_session_url, class: 'header-link right-side'

  li
    = link_to t('layouts.header.discover'), explore_path, class: 'header-link left-side'

  li
    = link_to t('layouts.header.submit'), start_path, class: 'header-link left-side'

  li
    = link_to t('layouts.header.help'), CatarseSettings[:support_forum], target: :_blank, class: 'header-link right-side',  id: 'guidelines_header_modal' if CatarseSettings[:support_forum].present?

app/views/custom/catarse_bootstrap/shared/_header_bootstrap_v1.html.slim
header
  .row
    .large-3.columns
      h1
        = link_to "#{CatarseSettings[:company_name]}", root_url(host: CatarseSettings[:base_domain] || request.domain), class: 'logo', :title => CatarseSettings[:company_name]
    .large-3.columns.call-to-action
      = link_to t('layouts.header.submit'), page_path(:how_it_works), :class => 'project'
      = link_to t('layouts.header.discover'), explore_path, :class => 'project'
    .large-3.columns
      = form_tag explore_path, :method => 'GET', :class=>'discover-form' do
        = text_field_tag :pg_search, nil, autocomplete: "off", value: params[:pg_search], class: "discover-form-input"
        = submit_tag
    .large-1.columns.user-utilities
      = link_to t('layouts.header.help'), CatarseSettings[:support_forum], target: :_blank, :class => 'header-nav-item',  id: 'guidelines_header_modal' if CatarseSettings[:support_forum].present?
      = link_to t('layouts.header.blog'), CatarseSettings['blog_url'], target: :_blank, class: 'header-nav-item' if CatarseSettings['blog_url'].present?

    .large-2.columns.user-dropdown
      - if current_user
        = link_to '#', class: 'user-menu' do
          = image_tag(current_user.display_image, :size => "40x40", class: 'user-avatar')
        ul.dropdown
          li= link_to t('layouts.header.profile'), current_user
          li= link_to t('layouts.user.my_contributions'), user_path(current_user, anchor: 'contributions')
          - if current_user.project_owner?
            li= link_to t('.projects'), user_path(current_user, anchor: 'projects')
          li
            = link_to t('layouts.user.my_credits'), user_path(current_user, anchor: 'credits')
            .small
              | (#{current_user.display_credits})
          li
            = link_to t('layouts.user.refund_link'), user_path(current_user, anchor: 'credits')
          - if current_user.admin? || current_user.channel
            li.divider
              - for menu, path in controller.menu do
                li= link_to menu, path
          li.divider= link_to t('layouts.user.logout'), destroy_user_session_path, method: :delete
      - else
        = link_to t('channels.header.signup'), new_user_registration_url, class: 'header-nav-item'
        = link_to t('channels.header.signin'), new_user_session_url, class: 'header-nav-item'

app/views/custom/catarse_bootstrap/shared/_header_channel.html.slim
header
  = content_for :meta_tags do
    -if ! @post
      meta property="og:title"        content= channel.name
    meta property="og:type"         content=:cause
    meta property="og:url"          content=url_for(only_path: false)
    meta property="og:image"        content=channel.image.curator_thumb.url
    meta property="og:site_name"    content=channel.name
    meta property="fb:app_id"       content=CatarseSettings[:facebook_app_id]
    meta property="og:description"  content=channel.description
  .row
    h1.large-2.columns.no-padding
      = link_to "#{CatarseSettings[:company_name]}", root_url(host: CatarseSettings[:base_domain] || request.domain), class: 'logo-image', :title => CatarseSettings[:company_name]
    .large-10.columns.no-padding
      nav.channel-header
        ul
          li.nav-item
            = link_to t('.how_work'), channels_about_path, id: 'guidelines_header_modal', class: 'standard-link-green'
          li.nav-item
            = link_to t('.posts'), channels_posts_path, class: 'standard-link'
          - if channel.partners.present?
            li.nav-item
              = link_to t('.partners'), root_url(anchor: 'partners'), class: 'standard-link'
          li.nav-item
            = mail_to channel.email, t('.contact'), title: t('.contact'), class: 'standard-link', target: '_blank'
          - if current_user
            li.nav-item
              = link_to '#', class: 'user-menu' do
                = image_tag(current_user.display_image, :size => "40x40", class: 'user-avatar')
              ul.dropdown.user
                li= link_to t('.profile'), current_user
                li= link_to t('layouts.user.my_contributions'), user_path(current_user, anchor: 'contributions')
                - if current_user.project_owner?
                  li= link_to t('.projects'), user_path(current_user, anchor: 'projects')
                li
                  = link_to t('.my_credits'), user_path(current_user, anchor: 'credits')
                  .small
                    | (#{current_user.display_credits})
                li
                  = link_to t('layouts.user.refund_link'), user_path(current_user, anchor: 'credits')
                - if current_user.admin? || current_user.channel
                  li.divider
                  - for menu, path in controller.menu do
                    li= link_to menu, path
                li.divider= link_to t('.logout'), destroy_user_session_path, method: :delete
          - else
            li.nav-item
              = link_to t('.signup'), new_user_registration_url, class: 'standard-link'
            li.nav-item
              = link_to t('.signin'), new_user_session_url, class: 'standard-link'

app/views/custom/catarse_bootstrap/shared/_project.html.slim
.large-3.columns.project-column
  = project.status_flag
  .project-box
    = link_to image_tag(project.display_image), project_by_slug_path(project.permalink), title: project.name, :class => 'image'
    .padding
      h4.title    = link_to truncate(project.name, length: 50, separator: ''), project_by_slug_path(project.permalink), title: project.name
      p.headline  = link_to truncate(project.headline, length: 140), project_by_slug_path(project.permalink), title: project.headline
    .status
      .padding
        p.progress-percent = t('projects.project.progress_html', percent: project.progress)
        .progress-bar     = project.progress_bar
        = link_to t('projects.project.time_remaining_html', count: project.time_to_go[:time], unit: project.time_to_go[:unit]), project_by_slug_path(project.permalink), title: project.name, class: 'time-remaining'
        = link_to t('projects.project.pledged_html', value: number_to_currency(project.pledged, precision: 0)), project_by_slug_path(project.permalink), title: project.name, class: 'money-raised'